
#   MODEL PARAMETERS

## PyTorch devices: "cpu", "cuda" or "cuda:{device_index}"
device: "cpu"

## Learning rate: https://en.wikipedia.org/wiki/Learning_rate
## In this implementation: a' = a - lr * gradient
## no additional manipulations to compute lr
lr: 0.01

## maximum number of iterations for model training
epochs: 1000

## Batch size: https://en.wikipedia.org/wiki/Stochastic_gradient_descent
## null - gradient descent: all values will be taken to calculate gradient
## 1 - stochastic gradient descent
## Other values are mini-batch or batch gradient descent
batch_size: 128

## Random seed to reproduce results.
## seed >= 0
## null - means no random seed
seed: 0

#   PREPROCESSING

## https://en.wikipedia.org/wiki/Feature_scaling
## "minmax" or "standard"
scale: "standard"

## Part of train dataset: 0 <= train_part <= 1
train_part: 0.8